### ISSUE TITLE
API rate limits and getting subtasks

### ISSUE THREAD

**Issue by 1cadumagalhaes** [ProofHub/api_v3#5]
Hello
We're using the API to build some custom reports about tasks, and we've encountered a problem with the limits.

The documentation says:
>  Rate limits are 50 requests per 10 second for the same account from the same IP

So I tried to add an timeout of 300 ms, and then I would make 33 requests in 10 seconds. But after a few requests (something near 10 or 15) I received the 429 status. 

That is a problem because when we want to fetch information about all tasks and its subtasks in a todolist, we keep getting the 429 error and need to wait until we try again. On average, we have tasks with 3 subtasks, wich means it will take 4 requests only to get this data.

**Comment by ProofHub** [comment]
Hi,

1. To get all subtasks of a task in a single request, you can use get-all-subtasks API. Here's the [link](https://github.com/ProofHub/api_v3/blob/master/sections/tasks.md#get-all-subtasks).

2. For the specific issue about getting 429 Response, please contact us on support@proofhub.com and share your ProofHub URL there, so that we can check for the issue.
